apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
    type: {{ .Values.deployment.type }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
        type: {{ .Values.deployment.type }}
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
  
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
      type: {{ .Values.deployment.type }}